# --- Main Settings ---
font=monospace:size=11
dpi-aware=auto
prompt="> "
icons-enabled=yes
show-actions=yes
terminal=foot

# --- Dimensions & Layout ---
width=40
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=10

[colors]
background=000000ff
text=ffffffff
match=ffffffff
selection=ffffffff
selection-text=000000ff
border=ffffffff

[border]
width=1
radius=0


[dmenu]
minimal-lines=yes
exit-immediately-if-empty=no
