#!/usr/bin/env bash
chosen=$(printf "lock\nlogout\nreboot\nshutdown" | fuzzel -d --no-exit-on-keyboard-focus-loss -p "power: ")

case "$chosen" in
    lock) swaylock --config ~/.config/swaylock/config ;;
    logout) swaymsg exit ;;
    reboot) systemctl reboot ;;
    shutdown) systemctl poweroff ;;
esac




























