#!/usr/bin/env bash

case "$1" in
    up)     brightnessctl set +1% ;;
    down)   brightnessctl set 1%- ;;
    max)    brightnessctl set 100% ;;
    min)    brightnessctl set 1% ;;
    status) brightnessctl -m | awk -F, '{gsub(/%/, "", $4); print $4 "%"}' ;;
    *)      exit 1 ;;
esac
