#!/usr/bin/env bash

case "${1:-datetime}" in
    time)
        date '+%H:%M'
        ;;

    date)
        date '+%a %d %b %Y'
        ;;

    datetime)
        date '+%a %d %b %Y  %H:%M'
        ;;

    iso)
        date '+%Y-%m-%d %H:%M:%S'
        ;;

    *)
        printf 'Usage: %s {time|date|datetime|iso}\n' "$0" >&2
        exit 1
        ;;
esac
